services:
  nclaw:
    image: ghcr.io/avlebedinsky/nclaw:${NCLAW_IMAGE_TAG:-claude}
    container_name: nclaw
    restart: unless-stopped
    environment:
      NCLAW_TELEGRAM_BOT_TOKEN: ${NCLAW_TELEGRAM_BOT_TOKEN}
      NCLAW_TELEGRAM_WHITELIST_CHAT_IDS: ${NCLAW_TELEGRAM_WHITELIST_CHAT_IDS}
      NCLAW_DATA_DIR: /app/data
      NCLAW_TIMEZONE: Europe/Moscow
      TZ: Europe/Moscow
      # NCLAW_WEBHOOK_BASE_DOMAIN: example.com
      # NCLAW_WEBHOOK_PORT: :3000
      RUTRACKER_USER: ${RUTRACKER_USER}
      RUTRACKER_PASS: ${RUTRACKER_PASS}
      OLLAMA_API_KEY: ${OLLAMA_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTP_PROXY}
    volumes:
      - ./data:/app/data
      - ${CLAUDE_CREDENTIALS_PATH}:/root/.claude/.credentials.json
      - ${CLAUDE_SKILLS_PATH:-./claude-skills}:/root/.claude/skills
      - ${AGENTS_PATH:-./agents}:/root/.agents
    # ports:
    #   - "3000:3000"  # Uncomment if using webhooks
